backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: false
publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img
locale: "pl"
site_url: https://justmemoriesphoto.pl
logo_url: https://justmemoriesphoto.pl/img/logo.png

collections:
  - name: "pages"
    label: "Strony"
    files:
      - file: "src/pages/index.md"
        label: "Strona główna"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Tytuł strony, name: title, widget: string }
          - { label: Nagłówek, name: heading, widget: string }
          - { label: Podtytuł, name: subheading, widget: string }
          - {
              label: "Wyrównanie nagłówka",
              name: "align",
              widget: "select",
              options:
                [
                  { label: "Do lewej", value: "left" },
                  { label: "Do środka", value: "center" },
                  { label: "Do prawej", value: "right" },
                ],
            }
          - { label: "Zdjęcie tytułowe", name: headerImage, widget: image }
          - { label: "Treść", name: body, widget: markdown }
          - { label: "Zdjęcie przed stopką", name: footerImage, widget: image }
      - file: "src/pages/o-mnie/index.md"
        label: "O mnie"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Tytuł strony", name: title, widget: string }
          - { label: "Nagłówek", name: heading, widget: string }
          - { label: "Opis", name: description, widget: string }
          - { label: "Zdjęcie", name: image, widget: image }
      - file: "src/pages/kontakt/index.md"
        label: "Kontakt"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: "Tytuł strony", name: title, widget: string }
          - { label: "Nagłówek", name: heading, widget: string }
          - { label: "Opis", name: description, widget: string }
          - { label: "Zdjęcie", name: image, widget: image }
  - name: "offers"
    label: "Oferta"
    label_singular: "wpis"
    folder: "src/pages/oferta"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "offer-page",
        }
      - { label: "Tytuł strony", name: title, widget: string }
      - { label: "Treść", name: body, widget: markdown }
  - name: "posts"
    label: "Realizacje"
    label_singular: "wpis"
    folder: "src/pages/realizacje"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "realization-post",
        }
      - { label: "Tytuł strony", name: title, widget: string }
      - { label: "Nagłówek", name: heading, widget: string }
      - { label: "Opis", name: description, widget: string }
      - { label: "Data publikacji", name: date, widget: datetime }
      - {
          label: "Zdjęcia",
          name: images,
          widget: list,
          min: 1,
          max: 100,
          field:
            { label: "Zdjęcie", name: image, widget: image, choose_url: false },
        }
