backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img
locale: 'pl'

collections:
  - name: "pages"
    label: "Strony"
    files:
      - file: "src/pages/index.md"
        label: "Strona główna"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: "Główny baner",
              name: intro,
              widget: object,
              fields: 
              [
                { label: Tytuł, name: heading, widget: string },
                { label: Podtytuł, name: subheading, widget: string },
                {
                  label: "Wyrównanie tytułu", 
                  name: "align", 
                  widget: "select",
                  options: 
                  [
                    { label: "Do lewej", value: "left" },
                    { label: "Do środka", value: "center" },
                    { label: "Do prawej", value: "right" },
                  ],
                },
                { label: "Zdjęcie w tle", name: image, widget: image },
              ]
            }
          - {
              label: Sekcja główna,
              name: main,
              widget: object,
              fields:
                [
                  { label: Nagłówek, name: heading, widget: string },
                  { label: Opis, name: description, widget: text },
                  {
                    label: Zdjęcia,
                    name: images,
                    widget: list,
                    fields:
                      [
                        { label: Zdjęcie, name: image, widget: image },
                        { label: Opis, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - { label: "Zdjęcie - stopka", name: footerImage, widget: image }
