backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img
locale: 'pl'

collections:
  - name: "pages"
    label: "Strony"
    files:
      - file: "src/pages/index.md"
        label: "Strona główna"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: "Główny baner",
              name: intro,
              widget: object,
              fields: 
              [
                { label: Tytuł, name: heading, widget: string },
                { label: Podtytuł, name: subheading, widget: string },
                {
                  label: "Wyrównanie tytułu", 
                  name: "align", 
                  widget: "select",
                  options: 
                  [
                    { label: "Do lewej", value: "left" },
                    { label: "Do środka", value: "center" },
                    { label: "Do prawej", value: "right" },
                  ],
                },
                { label: "Zdjęcie w tle", name: image, widget: image },
              ]
            }
          - {
              label: Sekcja główna,
              name: main,
              widget: object,
              fields:
                [
                  { label: Nagłówek, name: heading, widget: string },
                  { label: Opis, name: description, widget: text },
                  {
                    label: Zdjęcia,
                    name: images,
                    widget: list,
                    fields:
                      [
                        { label: Zdjęcie, name: image, widget: image },
                        { label: Opis, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - { label: "Zdjęcie - stopka", name: footerImage, widget: image }
      - file: "src/pages/oferta/index.md"
        label: "Oferta"
        name: "offer"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "offer-page",
            }
          - {
              label: "Pakiet",
              name: "session",
              widget: list,
              fields: 
              [
                { label: Tytuł, name: heading, widget: string },
                { label: Podtytuł, name: subheading, widget: string },
                { label: Opis, name: content, widget: markdown },
                { label: Koszt, name: price, widget: number },
              ],
            }
      - file: "src/pages/o-mnie/index.md"
        label: "O mnie"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Nagłówek", name: heading, widget: string }
          - { label: "Opis", name: content, widget: text }
          - { label: "Zdjęcie", name: image, widget: image }
  - name: "posts"
    label: "Portfolio"
    label_singular: "Album"
    folder: "src/pages/portfolio"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "portfolio-post",
        }
      - { label: "Tytuł", name: title, widget: string }
      - { label: "Opis", name: description, widget: string }
      - {
          label: "Zdjęcia",
          name: images,
          widget: list,
          field: {  label: "Zdjęcie", name: image, widget: image }
        }
